### ISSUE TITLE
Close Color Widget

### ISSUE THREAD

**Issue by gil--** [ekoeryanto/netlify-cms-widgets#15]
I feel the current color picker is huge:
<img width="859" alt="screen shot 2018-06-10 at 11 41 15 pm" src="https://user-images.githubusercontent.com/3484527/41211810-cdfa0678-6d07-11e8-9153-e10bd8d1c1f0.png">

Any reason it doesn't function like the native color picker where it shows the color picker once the input is selected?

### Shopify Example

![colorpicker](https://user-images.githubusercontent.com/3484527/41211850-1d8752ea-6d08-11e8-9db8-50231251bedd.gif)

----

I'll  look into forking and only showing the color picker when clicking on the input. Will try to PR perhaps?

**Comment by ekoeryanto** [comment]
> I feel the current color picker is huge

I agree with you. PR is welcome.

ref: http://casesandberg.github.io/react-color/#examples

When I moved netlify/netlify-cms#1242 here, I Thought about adding an option to toggle the type of the pickers (`AlphaPicker`, `BlockPicker`, `ChromePicker`, `CirclePicker`, etc.)
what you think?
