### ISSUE TITLE
Upgrade Font Awesome package versions

### ISSUE THREAD

**Issue by galvarez421** [ekoeryanto/netlify-cms-widgets#45]
Great widgets! I was just about to create a Font Awesome selector for Netlify CMS... Good thing I searched for an existing package first! =)

It looks like the current dependencies for the Font Awesome widget include deprecated Font Awesome npm packages, e.g., https://www.npmjs.com/package/@fortawesome/fontawesome and https://www.npmjs.com/package/@fortawesome/fontawesome-free-solid.

Would it be beneficial to upgrade the package to use non-deprecated dependencies per https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#no-more-default-imports?

**Comment by ekoeryanto** [comment]
Thanks for the issue,
